<img src=https://i.ibb.co/6gCsHd6/1200px-Pandas-logo-svg.png width="700" height="200">

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>



## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#4d77cf; font-size:200%; text-align:center; border-radius:10px 10px;">Pandas Series</p>

<a id="toc"></a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:center; border-radius:10px 10px;">Content</p>

* [IMPORTING LIBRARIES NEEDED IN THIS NOTEBOOK](#0)
* [CREATING PANDAS SERIES](#1)
    * [Using Lists](#1.1)
    * [Using Numpy Arrays](#1.2)
    * [Using Dictionaries](#1.3)
    * [Using Scalar Value](#1.4)
* [DATA IN A SERIES](#2)
* [BASIC ATTRIBUTES & METHODS OF SERIES](#3)
* [INDEXING AND SLICING WİTH PANDAS SERIES](#4)
* [Selection with Condition and Broadcasting](#5)
* [RECAP FOR SEVERAL SELECTING ATTRIBUTES](#6)
* [THE END OF THE SESSION-03](#7)

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Importing Libraries Needed in This Notebook</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Once you've installed NumPy & Pandas you can import them as a library:

In [4]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Creating a Pandas Series</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Pandas series is a one-dimensional data structure. It can hold data of many types including objects, floats, strings and integers. You can create a series by calling pandas.Series(). A list, numpy array, dict can be turned into a pandas series. You should use the simplest data structure that meets your needs [Source](https://pythonbasics.org/pandas-series/). The axis labels are collectively called index. Labels need not be unique but must be a hashable type. The object supports both integer and label-based indexing and provides a host of methods for performing operations involving the index [Source](https://www.geeksforgeeks.org/creating-a-pandas-series/).

[SOURCE01](https://pandas.pydata.org/docs/reference/api/pandas.Series.html), [SOURCE02](https://www.datasciencemadesimple.com/create-series-in-python-pandas/), 
[SOURCE03](https://www.cbsecsip.in/2020/08/pandas-data-structure-series.html), 
[SOURCE04](https://towardsdatascience.com/pandas-series-a-lightweight-intro-b7963a0d62a2), 
[SOURCE05](https://www.educba.com/pandas-series/), 
[SOURCE06](http://www.rebellionrider.com/python-pandas-series-in-detail-part-1/), 
[SOURCE06](https://www.javatpoint.com/python-pandas-series), &
[SOURCE06](https://towardsdatascience.com/20-examples-to-master-pandas-series-bc4c68200324)<br>

In this lecture we will discuss how to create Pandas Series, use basic attributes of Series, index Pandas Series & be familiar with Pandas Dataframes.

**You can create a series by calling pandas. Series() . A list, numpy array, dict and scalar value can be turned into a pandas series.**

**``pd.Series(data=None, index=None, dtype=None, name=None, copy=False, fastpath=False)``**

One-dimensional ndarray with axis labels (including time series).

In [5]:
labels = ['a', 'b', 'c']
my_list = [10, 20, 30]
arr = np.array([10, 20, 30])
d = {'a': 10, 'b': 20, 'c': 30}

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:center; border-radius:10px 10px;">Using Lists</p>

<a id="1.2.1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

**To turn a list into a series, all you have to do is:**

In [7]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [8]:
pd.Series([1,2,3,4,5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [13]:
pd.Series([1,2,3,4,5], index = "a,b,c,d,e".split(","), name = "first_series", dtype = float)

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
Name: first_series, dtype: float64

By default it assigns an index. First it shows the index, then the element value.

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:center; border-radius:10px 10px;">Using NumPy Arrays</p>

<a id="1.2.2"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

**You can create a series from a numpy ndarray.**

In [14]:
arr

array([10, 20, 30])

In [15]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int32

In [16]:
labels

['a', 'b', 'c']

In [17]:
ser1 = pd.Series(data = arr, index = labels)
ser1

a    10
b    20
c    30
dtype: int32

In [18]:
ser1 = pd.Series(data = arr, index = ['a', 'b', 'c','d'] )
ser1

ValueError: Length of values (3) does not match length of index (4)

```
pd.Series(data = arr, index = [1,2,3,4])
``` # the length of data and index must be same.

In [21]:
ser1.index

Index(['a', 'b', 'c'], dtype='object')

In [22]:
ser1.values

array([10, 20, 30])

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:center; border-radius:10px 10px;">Using Dictionaries</p>

<a id="1.2.3"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

**If you have a dictionary, you can turn it into a series:**

In [24]:
d

{'a': 10, 'b': 20, 'c': 30}

In [25]:
Series(d)  # the keys in dictionary are used as index

a    10
b    20
c    30
dtype: int64

It used the dictionary keys as index. The keys of the dictionary match with the Index values; hence, the default Index values have no effect.

In [28]:
Series(data = d, index = [1,2,3,"b","c"])

1     NaN
2     NaN
3     NaN
b    20.0
c    30.0
dtype: float64

Note that the Index is first build with the keys from the dictionary. After this the Series is reindexed with the given Index values, hence we get all NaN as a result.

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:center; border-radius:10px 10px;">Using Scalar Value</p>

<a id="1.2.4"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

**``Scalars``** are single values representing one unit of data, such as an integer or bool, as opposed to data structures like a list or tuple, which are composed of scalars.

If data is a scalar value, an index must be provided. The value will be repeated to match the length of index [Source](https://www.tutorialspoint.com/python_pandas/python_pandas_series.htm).

In [31]:
Series(data = "data science")

0    data science
dtype: object

In [32]:
Series(data = True,index=range(4))

0    True
1    True
2    True
3    True
dtype: bool

In [33]:
Series(data = False,index=["boolean"])

boolean    False
dtype: bool

In [34]:
Series(data = 10, index = list("abc"))  #  the broadcasting property in numpy ndarray

a    10
b    10
c    10
dtype: int64

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Data in a Series</p>

<a id="2"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

**``A series``** is a **one-dimensional data structure**. A Series is very **similar to a NumPy array** (in fact it is built on top of the NumPy array object). **What differentiates** the NumPy array from a Series, is that a Series can **have axis labels**, meaning it can be indexed by a label, instead of just a number location. It also doesn’t need to hold numeric data, it can hold any arbitrary Python Object [Source](http://www.datasciencelovers.com/python-for-data-science/pandas-series/).

So important point to remember for Pandas series is:

- Homogeneous data
- Size Immutable
- Values of Data Mutable

**A pandas Series can hold a variety of object types:**

In [35]:
Series(data = [set,list,dict,tuple])

0      <class 'set'>
1     <class 'list'>
2     <class 'dict'>
3    <class 'tuple'>
dtype: object

In [36]:
ser = Series(data = [set,list,dict,tuple])
ser

0      <class 'set'>
1     <class 'list'>
2     <class 'dict'>
3    <class 'tuple'>
dtype: object

In [37]:
ser[0]

set

In [39]:
ser[0]([1,3,3,4,4,5])

{1, 3, 4, 5}

In [40]:
type(ser.values)

numpy.ndarray

Even functions (although unlikely that you will use this)

In [41]:
Series(data = [sum,print,len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [42]:
ser = Series(data = [sum,print,len])
ser

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [43]:
ser[0]([1,2,3,4])  # sum function

10

In [44]:
ser[1]("Hello world!")

Hello world!


In [46]:
ser[2]("datascience")

11

In [47]:
# numpy arrays have Homogeneous data unlike Series.

In [48]:
mix_data = ["Ahmet",5,True,5.8]

In [50]:
ser = pd.Series(mix_data)
ser

0    Ahmet
1        5
2     True
3      5.8
dtype: object

when different values come together, the datatype becomes object.

In [51]:
ser.dtype

dtype('O')

In [52]:
type(ser)

pandas.core.series.Series

In [53]:
type(ser[0]), type(ser[1]), type(ser[2]), type(ser[3])  # In a dataframe, seem as dtype = object

(str, int, bool, float)

In [54]:
arr = np.array(mix_data)
arr

array(['Ahmet', '5', 'True', '5.8'], dtype='<U32')

In [55]:
arr.dtype

dtype('<U32')

In [56]:
type(arr[0]), type(arr[1]), type(arr[2]), type(arr[3])

(numpy.str_, numpy.str_, numpy.str_, numpy.str_)

In [57]:
mix_data2 = [5, 3.14]
ser3 = Series(mix_data2)
ser3

0    5.00
1    3.14
dtype: float64

In [60]:
mix_data2 = [5, "five",3.14,True]
ser3 = Series(mix_data2)
ser3

0       5
1    five
2    3.14
3    True
dtype: object

In [62]:
ser3.dtype

dtype('O')

In [68]:
for i in mix_data2:
    print(f"{i}: ", type(i))

5:  <class 'int'>
five:  <class 'str'>
3.14:  <class 'float'>
True:  <class 'bool'>


[Reminder Source for Numpy Arrays](https://pythonguides.com/python-numpy-data-types/)

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:center; border-radius:10px 10px;">BASIC ATTRIBUTES & METHODS OF SERIES</p>

<a id="3"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

**SOME COMMON ATTRIBUTES** [Official Pandas API Document](https://pandas.pydata.org/docs/reference/api/pandas.Series.html)<br>

**Series.dtype**	It returns the data type of the data.<br>
**Series.shape**	It returns a tuple of shape of the data.<br>
**Series.size**	    It returns the size of the data.<br>
**Series.ndim**	    It returns the number of dimensions in the data.<br>
**Series.index**	Defines the index of the Series.<br>
**Series.keys**  	Return alias for index.<br>
**Series.values**   Returns Series as ndarray or ndarray-like depending on the dtype.<br>
**Series.items**	Lazily iterate over (index, value) tuples.<br>
**Series.head**   	Return the first n rows.<br>
**Series.tail** 	Return the last n rows.<br>
**Series.sample**   Return a random sample of items from an axis of object.<br>
**Series.sort_index**  Sort Series by index labels.<br>
**Series.sort_values**  Sort by the values.<br>
**Series.isin**     Whether elements in Series are contained in values.<br>

In [69]:
ser = Series(data = np.random.randint(0,100,7))
ser

0    66
1     6
2    32
3    10
4    54
5    81
6    50
dtype: int32

In [70]:
type(ser)

pandas.core.series.Series

In [71]:
ser.dtype

dtype('int32')

In [72]:
ser.shape  # returns 7 rows

(7,)

In [73]:
ser.size  # Contains 7 elements

7

In [74]:
len(ser)  # returns 7 rows

7

In [75]:
ser.ndim  # returns the number of dimensions of the underlying data

1

In [76]:
ser

0    66
1     6
2    32
3    10
4    54
5    81
6    50
dtype: int32

In [78]:
ser.index  # returns the index of this series

RangeIndex(start=0, stop=7, step=1)

In [80]:
list(ser.index)

[0, 1, 2, 3, 4, 5, 6]

In [81]:
ser.keys()  # Return alias for index.


RangeIndex(start=0, stop=7, step=1)

In [82]:
list(ser.keys())

[0, 1, 2, 3, 4, 5, 6]

In [83]:
ser.values

array([66,  6, 32, 10, 54, 81, 50])

In [84]:
ser.items()

In [85]:
list(ser.items())

[(0, 66), (1, 6), (2, 32), (3, 10), (4, 54), (5, 81), (6, 50)]

another way to get the result above:

In [86]:
print(*ser.items(), sep='\t', end='\n') 
print(*ser.index, sep='\t', end='\n') 
print(*ser.values, sep='\t', end='\n') 

(0, 66)	(1, 6)	(2, 32)	(3, 10)	(4, 54)	(5, 81)	(6, 50)
0	1	2	3	4	5	6
66	6	32	10	54	81	50


In [87]:
ser = Series(data = np.random.randint(0,25,10), index = [i for i in "cadfgtyhks"])
ser  # we labeled the indexes ourselves

c    15
a    24
d     3
f     1
g     4
t    19
y    23
h     0
k    16
s     2
dtype: int32

In [88]:
# np.random.seed(101)
# ser = pd.Series(data=np.random.randint(0,25,10), index=[i for i in 'cdahfytrpq'])
# ser

In [89]:
ser.head()  # # returns the first 5 rows and default is 5

c    15
a    24
d     3
f     1
g     4
dtype: int32

In [90]:
ser.tail()  # returns the last 5 rows

t    19
y    23
h     0
k    16
s     2
dtype: int32

In [91]:
ser.sample(3)  # Return a random sample of items from an axis of object.

f     1
d     3
c    15
dtype: int32

In [92]:
ser.sort_index(ascending = True)

a    24
c    15
d     3
f     1
g     4
h     0
k    16
s     2
t    19
y    23
dtype: int32

In [93]:
ser.sort_index(ascending = False)

y    23
t    19
s     2
k    16
h     0
g     4
f     1
d     3
c    15
a    24
dtype: int32

In [94]:
ser.sort_index(ascending = False).head()

y    23
t    19
s     2
k    16
h     0
dtype: int32

In [95]:
ser.sort_values(ascending=True)

h     0
f     1
s     2
d     3
g     4
c    15
k    16
t    19
y    23
a    24
dtype: int32

In [96]:
ser.sort_values()

h     0
f     1
s     2
d     3
g     4
c    15
k    16
t    19
y    23
a    24
dtype: int32

In [97]:
ser.sort_values(ascending=False).tail(3)

s    2
f    1
h    0
dtype: int32

In [98]:
ser

c    15
a    24
d     3
f     1
g     4
t    19
y    23
h     0
k    16
s     2
dtype: int32

In [99]:
ser.isin([9,3])  
# Whether elements in Series are contained in `values`.
# Return a boolean Series showing whether each element in the Series
# matches an element in the passed sequence of `values` exactly.

c    False
a    False
d     True
f    False
g    False
t    False
y    False
h    False
k    False
s    False
dtype: bool

In [102]:
ser[ser.isin([9,3])]

d    3
dtype: int32

In [104]:
ser[ser.isin([16, 23, 24, 0,6])]

a    24
y    23
h     0
k    16
dtype: int32

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:center; border-radius:10px 10px;">Indexing and Slicing with Pandas Series</p>

<a id="4"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

As stated and implemented by examples above, a Series is very similar to a NumPy array. What differentiates the NumPy array from a Series is that **a Series can have axis labels**, meaning it can be indexed by a label, instead of just a number location. It also doesn’t need to hold numeric data, it can hold any arbitrary Python Object [Source](https://rpubs.com/pjozefek/659184).

The key to using a Series is understanding its index. Pandas makes use of these index names or numbers by allowing for fast look up of information.

The axis labeling information in pandas objects serves many purposes:

- Identifies data (i.e. provides metadata) using known indicators, important for analysis, visualization, and interactive console display.
- Enables automatic and explicit data alignment.
- Allows intuitive getting and setting of subsets of the data set.

In this section, we will focus on the final point: namely, how to slice, dice, and generally get and set subsets of pandas objects. The primary focus will be on Series and DataFrame as they have received more development attention in this area. For more information, please visit [pandas-docs.github.io](https://pandas-docs.github.io/pandas-docs-travis/user_guide/indexing.html)

Let's see some examples of how to grab information from a Series. Let us create two sereis, ser1 and ser2:

In [105]:
ser1 = pd.Series([1, 2, 3, 4], index = ['USA', 'Germany','RF', 'Japan'])
ser2 = pd.Series([1, 2, 5, 4, 6], index = ['USA', 'Germany','Italy', 'Japan', 'Spain'])

In [106]:
ser1

USA        1
Germany    2
RF         3
Japan      4
dtype: int64

In [107]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
Spain      6
dtype: int64

In [251]:
ser1.sort_index()

Germany    2
Japan      4
RF         3
USA        1
dtype: int64

In [252]:
 ser1.sort_values()

USA        1
Germany    2
RF         3
Japan      4
dtype: int64

In [253]:
ser1

USA        1
Germany    2
RF         3
Japan      4
dtype: int64

The two main data structures in pandas both have at least one axis. A **Series** has **one axis**, the index. A **DataFrame** has **two axes**, the index and the columns. It’s useful to note here that in all the DataFrame functions that can be applied to either rows or columns, an axis of 0 refers to the index, an axis of 1 refers to the columns.

**We're going to start with the basic form of selecting, using the [ ] operator.**

If we don’t introduce labels into our Series the index by default will be the natural numbers starting from 0. So the index will be the number of data introduced - 1.

In [109]:
ser1

USA        1
Germany    2
RF         3
Japan      4
dtype: int64

In [111]:
ser1.index

Index(['USA', 'Germany', 'RF', 'Japan'], dtype='object')

In [125]:
ser1[3]  # ser1.values[3], The value corresponding to the 3rd index

4

In [126]:
ser1["Japan"]  # we get the same result using label.

4

In [114]:
ser1.Japan  # This usage is not preferred.

4

In [119]:
ser1.index

Index(['USA', 'Germany', 'RF', 'Japan'], dtype='object')

In [120]:
ser1.index[3]

'Japan'

In [121]:
ser1.index.get_loc("Japan")

3

As seen above, with a Series, the call will return a single scalar value that matches the value at that label in the index. If you pass in a value for a label that doesn't exist, you will get a KeyError raised. Also, if you pass in an integer and your index has that value, it will return it. But if you don't have an integer value in your index, it will return the value by position. This is convenient, but can be confusing.

**Let's see some slicing example with Series**

In [127]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
Spain      6
dtype: int64

In [128]:
ser2[::-1]

Spain      6
Japan      4
Italy      5
Germany    2
USA        1
dtype: int64

In [129]:
ser2[1:3]

Germany    2
Italy      5
dtype: int64

**Another huge pro of using labelled indexes is that you can perform operations between two different series and pandas know what labels have both series in common and does the addition automatically.**

Operations are then also done based on index:

In [131]:
ser1 + ser2

Germany    4.0
Italy      NaN
Japan      8.0
RF         NaN
Spain      NaN
USA        2.0
dtype: float64

In [132]:
ser1 - ser2

Germany    0.0
Italy      NaN
Japan      0.0
RF         NaN
Spain      NaN
USA        0.0
dtype: float64

In [133]:
ser1 * ser2

Germany     4.0
Italy       NaN
Japan      16.0
RF          NaN
Spain       NaN
USA         1.0
dtype: float64

**Let's make changes on indexes:**

In [134]:
ser = pd.Series(data = [121, 200, 150, 99], index = ["terry", "micheal", "orion", "jason"])
ser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [136]:
ser.index

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [137]:
ser.values

array([121, 200, 150,  99], dtype=int64)

In [265]:
ser["terry"], ser[0], ser.terry, ser.index[0], ser.index.get_loc("terry")

(121, 121, 121, 'terry', 0)

In [266]:
ser[[0,2]], ser[["terry","orion"]]  # fancy indexing, returns the index more than one.

(terry    121
 orion    150
 dtype: int64,
 terry    121
 orion    150
 dtype: int64)

In [268]:
ser[0:3]

terry      121
micheal    200
orion      150
dtype: int64

In [269]:
ser["terry":"jason"]  # the difference from the above is that it contains exclusive (extreme) value.

terry      121
micheal    200
orion      150
jason       99
dtype: int64

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:center; border-radius:10px 10px;">Selection with Condition and Broadcasting</p>

<a id="5"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In [138]:
ser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [139]:
"terry" in ser  # searches in index

True

In [272]:
121 in ser

False

In [273]:
121 in ser.values

True

In [275]:
ser < 100

terry      False
micheal    False
orion      False
jason       True
dtype: bool

In [276]:
ser[ser < 100]

jason    99
dtype: int64

In [277]:
ser[ser < 100] = 100  # we assign permanently

In [278]:
ser 

terry      121
micheal    200
orion      150
jason      100
dtype: int64

In [285]:
ser.isin([121])

terry       True
micheal    False
orion      False
jason      False
dtype: bool

In [283]:
ser[ser.isin([121])]

terry    121
dtype: int64

In [284]:
ser[ser.isin([121])]

terry    121
dtype: int64

In [160]:
ser[ser.isin([121])].index

Index(['terry'], dtype='object')

In [161]:
ser[ser.isin([121])].index.get_loc("terry")

0

In [287]:
ser == 121

terry       True
micheal    False
orion      False
jason      False
dtype: bool

In [288]:
ser[ser==121]

terry    121
dtype: int64

In [291]:
ser.isin([100])

terry      False
micheal    False
orion      False
jason       True
dtype: bool

In [292]:
ser[ser.isin([100])]

jason    100
dtype: int64

In [293]:
ser[ser.isin([100])].index

Index(['jason'], dtype='object')

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:center; border-radius:10px 10px;">Recap for Several Selecting Attributes</p>

<a id="6"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In [289]:
ser

terry      121
micheal    200
orion      150
jason      100
dtype: int64

In [163]:
ser.keys()

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [164]:
ser.index

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [165]:
ser.values

array([121, 200, 150, 100], dtype=int64)

In [166]:
list(ser.items())

[('terry', 121), ('micheal', 200), ('orion', 150), ('jason', 100)]

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:150%; text-align:center; border-radius:10px 10px;">The End of The Session - 03</p>

<a id="7"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

___